# Generated by Django 4.2.6 on 2023-10-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
